// deploy.php
require 'recipe/laravel.php';

// Set up your server configuration
server('production', 'example.com')
    ->user('deploy')
    ->identityFile('~/.ssh/id_rsa')
    ->set('deploy_path', '/var/www/html');

// Set up your repository configuration
set('repository', 'git@github.com:user/repo.git');
set('branch', 'master');

// Set up your shared files and folders
add('shared_files', ['.env']);
add('shared_dirs', ['storage']);

// Set up your deployment tasks
task('deploy:composer', function () {
    run('cd {{release_path}} && composer install --no-dev --no-interaction --optimize-autoloader');
});
task('deploy:db', function () {
    run('cd {{release_path}} && php artisan migrate --force');
});
task('deploy:cache', function () {
    run('cd {{release_path}} && php artisan optimize');
});

// Set up your deployment workflow
before('deploy', 'deploy:prepare');
before('deploy:symlink', 'deploy:composer');
after('deploy:symlink', 'deploy:db');
after('deploy:symlink', 'deploy:cache');
